import { ReactNode } from "react";
import "./globals.css";
import Navbar from "../components/general/Navbar";
import { AuthProvider } from "@/components/general/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const header = (
  <Navbar />
)

const footer = (
  <div className="text-sm text-center">news-range platform. developed by: &Gamma;&Delta;&Beta;</div>
)

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
   <AuthProvider>
     <html lang="en">
      <body
        className='w-full max-w-7xl mx-auto min-h-screen flex flex-col px-4 sm:px-6 lg:px-8 bg-stone-200'>
          {header}
          {children}
          {footer}
      </body>
    </html>
   </AuthProvider>
  );
}
